--- dockerfiles/rpm.dockerfile  2021-06-17 08:18:53.228941305 +0000
+++ dockerfiles/rpm.dockerfile  2021-06-08 16:20:40.047490066 +0000
@@ -15,8 +15,8 @@
 #   See the License for the specific language governing permissions and
 #   limitations under the License.

-ARG BUILD_IMAGE=centos:7
-ARG BASE=centos
+ARG BUILD_IMAGE=ecos0003:5000/jenkins_slave_rhel:8.4
+ARG BASE=rhel
 ARG GOLANG_IMAGE=golang:latest

 # Install golang from the official image, since the package managed
@@ -30,7 +30,7 @@
 RUN go get github.com/cpuguy83/go-md2man/v2/@${MD2MAN_VERSION}

 FROM ${BUILD_IMAGE} AS redhat-base
-RUN yum install -y yum-utils rpm-build git
+RUN source /home/test/.bashrc && yum install -y yum-utils rpm-build git

 FROM redhat-base AS rhel-base
